name: pdf_viewer_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  # A package to show Native PDF View for iOS and Android, support Open from a different resource like Path, Asset or Url and Cache it.
  flutter_cached_pdfview: ^0.4.2
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

 
  uses-material-design: true

